# build path
[build]
  publish = "build"
  
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=604800"
